### ISSUE TITLE
README.md formatting borked (likely due to Github's md render update)

### ISSUE THREAD

**Issue by zbeekman** [nicjansma/saltthepass.js#2]
- https://github.com/blog/2333-a-formal-spec-for-github-flavored-markdown
 - https://githubengineering.com/a-formal-spec-for-github-markdown/

> Through synthetic analysis of GitHub’s massive Markdown corpus, we determined that less than 1% of the existing user content would be affected by the new implementation: we gathered these stats by rendering a large set of Markdown documents with both the old (Sundown) and the new (cmark, CommonMark compliant) libraries, normalizing the resulting HTML, and diffing their trees.

Looks like you're one of the lucky 1%!

**Comment by nicjansma** [comment]
Thanks for the heads up!

Looks like my named-anchors like this:

```
<a name="getHashes" />
### saltthepass.getHashes()
```

Needed to be inlined like this:

```
### saltthepass.getHashes() <a name="getHashes" />
```

Fixed!
