### ISSUE TITLE
Question/Feature request: npm installable CLI

### ISSUE THREAD

**Issue by zbeekman** [nicjansma/saltthepass.js#3]
I don't know how much work it would take, but it would be EPIC to have this as a npm installable command line interface.

BTW, nice idea. You totally scooped me as I have an implementation written in a compiled language that I use just for myself. I was contemplating open sourcing the engine part of it, and then perhaps trying to commercialize a full featured front end with bells and whistles (encrypted database of user names, domains/services, nonces, etc.) But I'm happy that this is open source and free.

![take my money](https://media.giphy.com/media/e3C4pNKkr9rji/giphy.gif)

**Comment by nicjansma** [comment]
Thanks Zaak!

I agree, that would be awesome.  I haven't built a NPM CLI before, but I like the idea a lot.  Will save this for a rainy day (unless you get to it first!? :) )

**Comment by pdl** [comment]
Dunno if either of you did this already, but I wanted a command line interface a couple of months earlier, and wrote it here: https://github.com/pdl/saltpass-cli

I have for some reason only just got around to actually putting it on npm: https://www.npmjs.com/package/saltpass-cli

**Comment by zbeekman** [comment]
Looks like it may be about that time to finally ditch my hand written (in a compiled language) alternative that pre-dates salt-the-pass and start using this. Probably need to store nonce and site name info in 1password so I don't lock myself out of everything.

@nicjansma let's close this issue, unless you want to build your own version.

**Comment by nicjansma** [comment]
Great work @pdl!
